# Предзагрузка изображения в память (укажите полный путь)
preload = /home/dmitrj/Изображения/wallpapers/1.jpg

# Установка на конкретный монитор
wallpaper = ,/dmitrj/Изображения/wallpapers/1.jpg

# Выключить текст "splash" (цитаты снизу)
splash = false
